Table users {
  id bigint [pk, increment]
  name string [not null]  // Name of the user
  email string [not null]  // Email of the user
  password_digest string [not null]  // Encrypted password of the user
  tags text [array]
  created_at datetime [not null]  // Timestamp of when the user was created
  updated_at datetime [not null]  // Timestamp of when the user was last updated
}

Table posts {
  id bigint [pk, increment]
  title string [not null]  // Title of the post
  content text [not null]  // Content of the post
  internal_description text  // Internal description
  user_id bigint [not null] [ref: > users.id]  // Foreign key of the user who created the post
  created_at datetime [not null]  // Timestamp of when the post was created
  updated_at datetime [not null]  // Timestamp of when the post was last updated
}

Table comments {
  id bigint [pk, increment]
  content text [not null]  // Content of the comment
  user_id bigint [not null] [ref: > users.id]  // Foreign key of the user who created the comment
  post_id bigint [not null] [ref: > posts.id]  // Foreign key of the post that the comment belongs to
  created_at datetime [not null]  // Timestamp of when the comment was created
  updated_at datetime [not null]  // Timestamp of when the comment was last updated
}

Ref: comments.post_id > posts.id
Ref: comments.user_id > users.id
Ref: posts.user_id > users.id
